
CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 91) NOT NULL,
    name       VARCHAR                                                  NOT NULL,
    email      VARCHAR                                                  NOT NULL,
    age        SMALLINT                                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);